import React,{useEffect,useMemo,useState} from 'react';
import {Menu,X,Search,ExternalLink,ChevronDown} from 'lucide-react';
import {siteMenu} from '../data/site';
import {defaultSiteConfig} from '../data/defaultSiteConfig';
import {api} from '../lib/api';

export function Shell({children,currentPath}:{children:React.ReactNode,currentPath:string}){
 const [open,setOpen]=useState(false),[searchOpen,setSearchOpen]=useState(false),[query,setQuery]=useState(''),[cfg,setCfg]=useState<any>(defaultSiteConfig),[menu,setMenu]=useState<any[]>(siteMenu);
 useEffect(()=>{api('/site/config').then(r=>{if(!r.ok)return;setCfg({...defaultSiteConfig,...(r.data||{})});try{const m=JSON.parse(r.data?.navigation_json||'[]');if(Array.isArray(m)&&m.length)setMenu(m)}catch{}})},[]);
 useEffect(()=>{setOpen(false);setSearchOpen(false)},[currentPath]);
 useEffect(()=>{const apply=()=>{document.querySelectorAll<HTMLAnchorElement>('a[href]').forEach(a=>{try{const u=new URL(a.href,location.href);if(/^https?:$/.test(u.protocol)&&u.origin!==location.origin){a.target='_blank';a.rel='noopener noreferrer'}}catch{}})};apply();const ob=new MutationObserver(apply);ob.observe(document.body,{subtree:true,childList:true});return()=>ob.disconnect()},[]);
 const logo=cfg.logo_key||'/brand/nhn-logo-2026.png';
 const searchItems=useMemo(()=>menu.flatMap((m:any)=>[{label:m.label,path:m.path},...((m.children||[]).map((c:any)=>typeof c==='string'?{label:c,path:`${m.path}#${encodeURIComponent(c)}`}:{label:c.label,path:c.path}))]),[menu]);
 const results=query.trim()?searchItems.filter((x:any)=>x.label.toLocaleLowerCase('vi').includes(query.trim().toLocaleLowerCase('vi'))).slice(0,8):searchItems.slice(0,8);
 return <div className="site-shell" style={{'--red':cfg.primary_color||'#9d1820','--gold':cfg.accent_color||'#c59a3d'} as React.CSSProperties}>
  <header className="topbar"><div className="container topbar-inner"><span>{cfg.site_name||'Nhà Hán Ngữ'} · Học tập · Kết nối · Phát triển</span><a href={cfg.app_url||'https://app.nhahanngu.io.vn'} target="_blank" rel="noopener noreferrer">APP Nhà Hán Ngữ <ExternalLink size={13}/></a></div></header>
  <header className="header"><div className="container header-inner"><a className="brand" href="/"><img src={logo} onError={e=>{e.currentTarget.src='/brand/nhn-logo-2026.png'}} alt="Logo Nhà Hán Ngữ"/><div><strong>{cfg.site_name||'NHÀ HÁN NGỮ'}</strong><span>{cfg.tagline||'Kết nối tri thức • Mở lối tương lai'}</span></div></a>
   <nav className="nav desktop-nav">{menu.slice(0,8).map((m:any)=><div className="nav-item" key={m.path}><a className={currentPath===m.path?'active':''} href={m.path}>{m.label}{m.children&&<ChevronDown size={14}/>}</a>{m.children&&<div className="mega">{m.children.map((c:any)=><a key={typeof c==='string'?c:c.label} href={typeof c==='string'?`${m.path}#${encodeURIComponent(c)}`:c.path}>{typeof c==='string'?c:c.label}</a>)}</div>}</div>)}</nav>
   <div className="header-actions"><button className="icon-btn" aria-label="Tìm kiếm" onClick={()=>setSearchOpen(true)}><Search size={19}/></button><a className="btn btn-outline" href="/tra-cuu">Tra cứu mã</a><button className="menu-btn" aria-label="Mở menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></div>
   {open&&<div className="mobile-nav container">{menu.map((m:any)=><div className="mobile-nav-group" key={m.path}><a href={m.path}>{m.label}</a>{Array.isArray(m.children)&&m.children.length>0&&<div className="mobile-subnav">{m.children.map((c:any)=><a key={typeof c==='string'?c:c.label} href={typeof c==='string'?`${m.path}#${encodeURIComponent(c)}`:c.path}>{typeof c==='string'?c:c.label}</a>)}</div>}</div>)}</div>}
  </header>
  {searchOpen&&<div className="search-overlay" role="dialog" aria-modal="true" aria-label="Tìm kiếm"><button className="search-backdrop" aria-label="Đóng tìm kiếm" onClick={()=>setSearchOpen(false)}/><div className="search-panel"><div className="search-box"><Search size={20}/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Tìm trang, học liệu, làm bài tập…"/><button className="icon-btn" onClick={()=>setSearchOpen(false)} aria-label="Đóng"><X/></button></div><div className="search-results">{results.length?results.map((r:any)=><a key={`${r.path}-${r.label}`} href={r.path}><Search size={15}/><span>{r.label}</span></a>):<p>Không tìm thấy mục phù hợp.</p>}</div></div></div>}
  <main id="main-content" tabIndex={-1}>{children}</main>
  <footer className="footer"><div className="container footer-grid"><div><img src={logo} onError={e=>{e.currentTarget.src='/brand/nhn-logo-2026.png'}} className="footer-logo" alt="Logo Nhà Hán Ngữ"/><p>{cfg.footer_description||'Không gian học tập, chia sẻ và kết nối dành cho cộng đồng quan tâm đến Hán ngữ và tiếng Trung.'}</p></div><div><h4>Khám phá</h4><a href="/hoc-han-ngu">Học Hán Ngữ</a><a href="/kho-hoc-lieu">Kho học liệu</a><a href="/thi-thu">Làm bài tập</a><a href="/kien-thuc">Kiến thức</a></div><div><h4>Kết nối</h4><a href="/tham-gia">Tham gia</a><a href="/cong-dong">Cộng đồng</a><a href="/doi-tac">Đối tác</a><a href="/lien-he">Liên hệ</a><a href="/tra-cuu">Tra cứu mã</a><a href={cfg.app_url||'https://app.nhahanngu.io.vn'} target="_blank" rel="noopener noreferrer">APP Nhà Hán Ngữ</a></div></div><div className="container footer-bottom">© 2026 Nhà Hán Ngữ · Đơn vị thuộc Mạng lưới Giáo dục & Phát triển Cộng đồng Sky First</div></footer>
 </div>
}
