import React from 'react';
import {ArrowRight,BookOpen,GraduationCap,Headphones,Library,Users,CalendarDays,Search} from 'lucide-react';
import {examGroups,learningCards} from '../data/site';
export function Home(){return <>
<section className="hero"><div className="container hero-grid"><div><div className="eyebrow">NHÀ HÁN NGỮ · 中文学习社区</div><h1>Học Hán ngữ theo một hành trình <em>rõ ràng, thực tế và có cộng đồng.</em></h1><p>Nhà Hán Ngữ xây dựng không gian học tập, học liệu, thi thử và hoạt động cộng đồng dành cho người học tiếng Trung ở nhiều cấp độ.</p><div className="hero-actions"><a className="btn btn-primary" href="/hoc-han-ngu">Bắt đầu học <ArrowRight size={18}/></a><a className="btn btn-ghost" href="/thi-thu">Thi thử trực tuyến</a></div><div className="hero-stats"><span><b>260</b> đề luyện</span><span><b>13.000+</b> câu hỏi mục tiêu</span><span><b>HSK 1–9</b> lộ trình</span></div></div><div className="hero-card"><div className="stamp">汉</div><img src="/brand/nhn-logo.jpg"/><h3>Nhà Hán Ngữ</h3><p>Kết nối tri thức • Mở lối tương lai</p><div className="mini-grid"><div><BookOpen/>Bài học</div><div><Library/>Học liệu</div><div><GraduationCap/>Thi thử</div><div><Users/>Cộng đồng</div></div></div></div></section>
<section className="section"><div className="container"><div className="section-head"><div><span className="kicker">HỌC TẬP</span><h2>Một hệ sinh thái học Hán ngữ có chiều sâu</h2></div><a href="/hoc-han-ngu">Xem toàn bộ <ArrowRight size={16}/></a></div><div className="card-grid">{learningCards.map(([t,d,a])=><article className="feature-card" key={t}><span className="han-chip">{a}</span><h3>{t}</h3><p>{d}</p><a href="/hoc-han-ngu">Khám phá <ArrowRight size={15}/></a></article>)}</div></div></section>
<section className="section section-soft"><div className="container"><div className="section-head"><div><span className="kicker">THI THỬ</span><h2>Luyện tập trực tiếp trên website</h2><p>Đề thi được tổ chức theo nhóm, cấp độ và kỹ năng; hỗ trợ chấm điểm, xem đáp án, giải thích và phân tích kết quả.</p></div></div><div className="exam-grid">{examGroups.map(g=><a className="exam-card" href={`/thi-thu?group=${g.id}`} key={g.id}><span className="exam-han">{g.accent}</span><div><h3>{g.title}</h3><p>{g.description}</p></div><ArrowRight/></a>)}</div></div></section>
<section className="section"><div className="container two-col"><div><span className="kicker">HOẠT ĐỘNG MỚI</span><h2>Học không chỉ trong bài học</h2><p className="lead">Nhà Hán Ngữ định hướng tổ chức các chuyên đề, workshop, hoạt động giao lưu, cuộc thi và chương trình cộng đồng để người học có thêm môi trường sử dụng ngôn ngữ và kết nối.</p><a className="btn btn-outline" href="/tin-tuc-su-kien">Xem tin & sự kiện</a></div><div className="timeline-cards"><div><CalendarDays/><div><b>Workshop & chuyên đề</b><span>Kiến thức, kỹ năng, phương pháp học tập</span></div></div><div><Headphones/><div><b>Luyện nghe & giao tiếp</b><span>Tình huống thực tế, phản xạ và phát âm</span></div></div><div><Search/><div><b>Khám phá Hán ngữ</b><span>Chữ Hán, thành ngữ, văn hóa và lịch sử</span></div></div></div></div></section>
<section className="cta"><div className="container"><div><span className="kicker light">CỘNG ĐỒNG NHÀ HÁN NGỮ</span><h2>Cùng học, cùng chia sẻ, cùng phát triển.</h2><p>Tham gia các chương trình, hoạt động và cơ hội cộng tác phù hợp với bạn.</p></div><a className="btn btn-light" href="/cong-dong">Tham gia Nhà Hán Ngữ <ArrowRight size={17}/></a></div></section>
</>}
