import React,{useEffect,useState} from 'react';
import {api} from '../lib/api';
import {ArrowRight,BookOpen,GraduationCap,Headphones,Library,Users,CalendarDays,Search} from 'lucide-react';
import {examGroups,learningCards} from '../data/site';
export function Home(){const [cfg,setCfg]=useState<Record<string,string>>({});const [posts,setPosts]=useState<any[]>([]);useEffect(()=>{api('/site/config').then(r=>r.ok&&setCfg(r.data||{}));api('/public/cms/posts').then(r=>r.ok&&setPosts((r.data||[]).slice(0,3)))},[]);const sections=(()=>{try{const x=JSON.parse(cfg.homepage_sections_json||'[]');return Array.isArray(x)&&x.length?x:['learning','exams','activities','community']}catch{return ['learning','exams','activities','community']}})();const show=(x:string)=>sections.includes(x);const heroTitle=cfg.homepage_hero_title||'Học Hán ngữ theo một hành trình rõ ràng, thực tế và có cộng đồng.';const heroDesc=cfg.homepage_hero_description||'Nhà Hán Ngữ xây dựng không gian học tập, học liệu, làm bài tập và hoạt động cộng đồng dành cho người học tiếng Trung ở nhiều cấp độ.';return <>
<section className="hero"><div className="container hero-grid"><div><div className="eyebrow">NHÀ HÁN NGỮ · 中文学习社区</div><h1>{heroTitle}</h1><p>{heroDesc}</p><div className="hero-actions"><a className="btn btn-primary" href="/hoc-han-ngu">Bắt đầu học <ArrowRight size={18}/></a><a className="btn btn-ghost" href="/thi-thu">Làm bài tập trực tuyến</a></div><div className="hero-stats"><span><b>180</b> bài luyện HSK</span><span><b>20</b> bài mỗi cấp</span><span><b>HSK 1–9</b> lộ trình</span></div></div><div className="hero-card"><div className="stamp">汉</div><img src={cfg.homepage_hero_image||'/brand/nhn-logo-2026.png'} alt="Nhà Hán Ngữ"/><h3>Nhà Hán Ngữ</h3><p>Kết nối tri thức • Mở lối tương lai</p><div className="mini-grid"><div><BookOpen/>Bài học</div><div><Library/>Học liệu</div><div><GraduationCap/>Làm bài tập</div><div><Users/>Cộng đồng</div></div></div></div></section>
{show('learning')&&<section className="section"><div className="container"><div className="section-head"><div><span className="kicker">HỌC TẬP</span><h2>Học Hán ngữ theo từng mục tiêu rõ ràng</h2></div><a href="/hoc-han-ngu">Xem toàn bộ <ArrowRight size={16}/></a></div><div className="card-grid">{learningCards.map(([t,d,a])=><article className="feature-card" key={t}><span className="han-chip">{a}</span><h3>{t}</h3><p>{d}</p><a href="/hoc-han-ngu">Khám phá <ArrowRight size={15}/></a></article>)}</div></div></section>}
{show('exams')&&<section className="section section-soft"><div className="container"><div className="section-head"><div><span className="kicker">LÀM BÀI TẬP</span><h2>Luyện tập trực tiếp trên website</h2><p>Bài tập được sắp xếp theo cấp độ và kỹ năng; hỗ trợ chấm điểm, xem đáp án, giải thích và theo dõi kết quả luyện tập.</p></div></div><div className="exam-grid">{examGroups.map(g=><a className="exam-card" href={`/thi-thu?group=${g.id}`} key={g.id}><span className="exam-han">{g.accent}</span><div><h3>{g.title}</h3><p>{g.description}</p></div><ArrowRight/></a>)}</div></div></section>}
{show('activities')&&<section className="section"><div className="container"><div className="section-head"><div><span className="kicker">BẢNG TIN MỚI</span><h2>Cập nhật từ Nhà Hán Ngữ</h2></div><a href="/tin-tuc-su-kien">Xem toàn bộ <ArrowRight size={16}/></a></div>{posts.length?<div className="news-grid">{posts.map(x=><a className="news-card" href="/tin-tuc-su-kien" key={x.id}>{x.data?.cover_url?<img src={x.data.cover_url} alt=""/>:<div className="news-placeholder">NHN</div>}<div className="news-card-body"><span className="news-chip">{x.data?.category||'Bảng tin'}</span><h2>{x.title}</h2><p>{x.data?.excerpt||'Xem nội dung mới từ Nhà Hán Ngữ.'}</p></div></a>)}</div>:<div className="timeline-cards"><div><CalendarDays/><div><b>Workshop & chuyên đề</b><span>Kiến thức, kỹ năng, phương pháp học tập</span></div></div><div><Headphones/><div><b>Luyện nghe & giao tiếp</b><span>Tình huống thực tế, phản xạ và phát âm</span></div></div><div><Search/><div><b>Khám phá Hán ngữ</b><span>Chữ Hán, thành ngữ, văn hóa và lịch sử</span></div></div></div>}</div></section>}
{show('community')&&<section className="cta"><div className="container"><div><span className="kicker light">CỘNG ĐỒNG NHÀ HÁN NGỮ</span><h2>Cùng học, cùng chia sẻ, cùng phát triển.</h2><p>Tham gia các chương trình, hoạt động và cơ hội cộng tác phù hợp với bạn.</p></div><a className="btn btn-light" href="/tham-gia">Tham gia Nhà Hán Ngữ <ArrowRight size={17}/></a></div></section>}
</>}
